#!/usr/bin/env bash
echo "hello"
echo $BASH
mkdir -p ~/.vim/pack/plugins/start
git clone https://github.com/justinmk/vim-dirvish .vim/pack/plugins/start/vim-dirvish
git clone https://github.com/junegunn/fzf.vim .vim/pack/plugins/start/fzf.vim
git clone https://github.com/airblade/vim-gitgutter .vim/pack/plugins/start/vim-gitgutter
