vo=gpu
hwdec=auto
profile=fast

keep-open=no
save-position-on-quit=yes
resume-playback=yes

osc=no
border=no

cache=no

audio-display=no

demuxer-max-bytes=16MiB
demuxer-max-back-bytes=8MiB

vd-lavc-threads=1

ytdl=no
autoload-files=no
sub-auto=no
audio-file-auto=no

config=yes

fullscreen=yes
